apiVersion: v1
kind: Pod
metadata:
  name: app-livenessprob
  namespace: demo
spec:
  containers:
    - image: us-central1-docker.pkg.dev/chip-k8s/devops/demo:v1.0.0
      name: app

      livenessProbe:
        httpGet:
          path: /
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
        
      ports:
        - containerPort: 8080
          name: http
