name: KBOT-CICD # Ім"я пайплайну

on: push # Запускати пайплайн при push події

env:
  APP: "kbot"
  REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest # запускати завдання на останній версії убунту

    steps:
      - name: Checkout # стандартний перший степ перевірки
        uses: actions/checkout@v3 # Це дія, яка перевіряє ваше сховище та завантажує його в програму запуску, дозволяючи вам виконувати дії з вашим кодом
        with:
          fetch-depth: 0 # Number of commits to fetch. 0 indicates all history for all branches and tags.

      - name: Run test
        run: make test # запускаємо команду тест з Makefile в корені проекту

      - name: Docker Hub login
        uses: docker/login-action@v1
        with: # settings/secrets/actions
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push image
        run: make image push

